INSERT INTO STATE VALUES(1,'Stockholm',48);
INSERT INTO STATE VALUES(2,'Västerbotten',48);
INSERT INTO STATE VALUES(3,'Norrbotten',48);
INSERT INTO STATE VALUES(4,'Uppsala',48);
INSERT INTO STATE VALUES(5,'Södermanland',48);
INSERT INTO STATE VALUES(6,'Östergötland',48);
INSERT INTO STATE VALUES(7,'Jönköping',48);
INSERT INTO STATE VALUES(8,'Kronoberg',48);
INSERT INTO STATE VALUES(9,'Kalmar',48);
INSERT INTO STATE VALUES(10,'Gotland',48);
INSERT INTO STATE VALUES(11,'Blekinge',48);
INSERT INTO STATE VALUES(12,'Skåne',48);
INSERT INTO STATE VALUES(13,'Halland',48);
INSERT INTO STATE VALUES(14,'Västra Götaland',48);
INSERT INTO STATE VALUES(15,'Värmland',48);
INSERT INTO STATE VALUES(16,'Örebro',48);
INSERT INTO STATE VALUES(17,'Västmanland',48);
INSERT INTO STATE VALUES(18,'Dalarna',48);
INSERT INTO STATE VALUES(19,'Gävleborg',48);
INSERT INTO STATE VALUES(20,'Västernorrland',48);
INSERT INTO STATE VALUES(21,'Jämtland',48);









