CREATE TABLE IF NOT EXISTS continent (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS COUNTRY (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name TEXT,
	continent INTEGER,
	FOREIGN KEY(continent) REFERENCES CONTINENT(id)
);
CREATE TABLE IF NOT EXISTS VISIT(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	country INTEGER,
	start_day INTEGER,
	start_month INTEGER,
	start_year INTEGER,
	end_day INTEGER,
	end_month INTEGER,
	end_year INTEGER,
	FOREIGN KEY(country) REFERENCES COUNTRY(id)

);
